### ISSUE TITLE
Latest builds fail on docker hub

### ISSUE THREAD

**Issue by timelf123** [hasable/docker-arma3-mods#1]

**Comment by hasable** [comment]
Hi, 

I am aware of that. Failure due to not enough disk space to build image. I will probably have to rethink the build process. 

H.

**Comment by hasable** [comment]
I remove CUP and R3F from the image to gain space (this image is now quite useless 👎 ).

To use CUP and R3F, you will have to download it by yourself, and mount directory in the container : 
    volumes:
      - /opt/black-company/mods/@CUP_Units:/opt/arma3/@CUPUnits
      - /opt/black-company/mods/@CUP_Units/keys/cup_units-1.10.1.bikey:/opt/arma3/keys/cup_units-1.10.1.bikey
      - /opt/black-company/mods/@CUP_Vehicles:/opt/arma3/@CUPVehicles
      - /opt/black-company/mods/@CUP_Vehicles/keys/cup_vehicles-1.10.1.bikey:/opt/arma3/keys/cup_vehicles-1.10.1.bikey
      - /opt/black-company/mods/@CUP_Weapons:/opt/arma3/@CUPWeapons
      - /opt/black-company/mods/@CUP_Weapons/keys/cup_weapons-1.10.1.bikey:/opt/arma3/keys/cup_weapons-1.10.1.bikey
      - /opt/black-company/mods/@R3F_ARMES:/opt/arma3/@R3FArmes
      - /opt/black-company/mods/@R3F_ARMES/server_key/r3f.bikey:/opt/arma3/keys/r3fa.bikey
      - /opt/black-company/mods/@R3F_UNITES:/opt/arma3/@R3FUnites
      - /opt/black-company/mods/@R3F_UNITES/server_key/r3f.bikey:/opt/arma3/keys/r3fu.bikey

Tested and approved 🥇 

H.
